### ISSUE TITLE
Wining condition is wrong

### ISSUE THREAD

**Issue by GuoqiangXu** [bigeyex/GoldenRightHandTest#2]
1. The winning condition can not be correctly calculated after the version "bug fix: remove monster when it's out of bound". 
2. The evading behavior of monsters sometime make them move out the right screen boundary, in this case, the monster needs not to be removed. Therefore, we need to only remove monster that move out the left boundary.
3. The [uiScoreBoard giveStarForReason:xxx]; or something related to these objects caused a lot of crashes when I run the tests.

**Comment by GuoqiangXu** [comment]
The first bug has been fixed. Regarding the 3rd one, the error message is "Terminating app due to uncaught exception 'Out of Star Capacity', reason: 'You give stars out of scoreboard capacity'"

**Comment by GuoqiangXu** [comment]
the 2nd issue has been dealt with.

**Comment by bigeyex** [comment]
made defensive action towards 3rd bug. Reopen this issue when it further appears.
